name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on push to main
  workflow_dispatch:  # Enables manual trigger in GitHub Actions UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run quick-build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist  # Change if needed

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
